// place-test1m: test 1's Blurry flow, syllable errors measured over all syllables in sheet order (so a page that merges
// lines can be compared with the original). Same synthetic 76 bpm track and voice as place-test1.
var BLURRY_LRC = "[00:23.09] Everything's so blurry and everyone's so fake\n[00:28.96] And everybody's empty and everything is so messed up\n[00:34.96] Preoccupied without you, I cannot live at all\n[00:41.24] My whole world surrounds you, I stumble and I crawl\n[00:47.21] You could be my someone, you could be my scene\n[00:53.37] You know that I'll protect you from all of the obscene\n[00:59.31] I wonder what you're doing, imagine where you are\n[01:05.42] There's oceans in between us, but that's not very far\n[01:12.94] Can you take it all away?\n[01:15.94] Can you take it all away?\n[01:19.01] Well, you shoved it in my face\n[01:22.25] This pain you gave to me\n[01:25.18] Can you take it all away?\n[01:28.23] Can you take it all away?\n[01:31.16] Well, you shoved it in my face\n[01:36.25] Everyone is changing, there's no one left that's real\n[01:42.19] So make up your own ending and let me know just how you feel\n[01:48.22] 'Cause I am lost without you, I cannot live at all\n[01:54.46] My whole world surrounds you, I stumble then I crawl\n[02:00.67] You could be my someone, you could be my scene\n[02:06.55] You know that I will save you from all of the unclean\n[02:12.76] I wonder what you're doing, I wonder where you are\n[02:18.70] There's oceans in between us, but that's not very far\n[02:26.18] Can you take it all away?\n[02:29.33] Can you take it all away?\n[02:32.30] Well, you shoved it in my face\n[02:35.57] This pain you gave to me\n[02:38.45] Can you take it all away?\n[02:41.52] Can you take it all away?\n[02:44.40] Well, you shoved it in my face\n[02:47.95] This pain you gave to me\n[02:51.16] \n[03:01.91] Nobo-, nobody told me what you thought\n[03:06.17] Nobody told me what to say\n[03:09.11] Everyone showed you where to turn\n[03:12.36] Told you when to run away\n[03:15.48] Nobody told you where to hide\n[03:18.49] Nobody told you what to say\n[03:21.57] Everyone showed you where to turn\n[03:24.30] Showed you when to run away\n[03:27.13] Can you take it all away?\n[03:30.21] Can you take it all away?\n[03:33.21] Well, you shoved it in my face\n[03:36.48] This pain you gave to me\n[03:39.30] Can you take it all away?\n[03:42.35] Can you take it all away?\n[03:45.45] Well, you shoved it in my face\n[03:48.85] This pain you gave to me, no\n[03:53.59] \n[03:56.55] This pain you gave to me\n[03:59.80] \n[04:08.78] This pain you gave to me\n[04:12.54] \n[04:19.52] Can you take it all, take it all away?\n[04:24.32] This pain you gave to me\n[04:27.03] Can you take it all away?\n[04:30.29] This pain you gave to me\n[04:32.93] Can you take it all away?\n[04:36.10] This pain you gave to me\n[04:37.40] ";
var d = window.__ds;
function say(t) { var o = document.getElementById('__out'); if (o) o.textContent += '\n' + t; else __lines.push(t); }
function check(name, ok, detail) { say((ok ? 'PASS ' : 'FAIL ') + name + (detail ? ': ' + detail : '')); }
function r2(x) { return Math.round(x * 100) / 100; }
function r3(x) { return Math.round(x * 1000) / 1000; }
var fps = 100, DUR = 304, N = fps * DUR, BPM = 76, BEAT = 60 / BPM, T0 = 1.0, SIXTEENTH = BEAT / 4;
var toasts = []; (function () { var t = document.getElementById('toast'); new MutationObserver(function () { toasts.push(t.textContent); }).observe(t, { childList: true, characterData: true, subtree: true }); })();
function bump(env, t, amp, decay) { var k0 = Math.round(t * fps), k; for (k = 0; k < decay && k0 + k < env.length; k++) { var v = (k < 2 ? amp * (k + 1) / 2 : amp * (1 - (k - 2) / (decay - 2))); if (v > env[k0 + k]) env[k0 + k] = v; } }
function sing(env, on, off) { var k0 = Math.round(on * fps), k1 = Math.round(off * fps), f; if (k0 < env.length && env[k0] < 1.4) env[k0] = 1.4; for (f = k0 + 1; f < k1 && f < env.length; f++) if (env[f] < 2.3) env[f] = 2.3; }
var full = new Float32Array(N), low = new Float32Array(N), voice = new Float32Array(N), i, k = 0, t;
for (i = 0; i < N; i++) { full[i] = 0.5; low[i] = 0.4; voice[i] = 0.4; }
for (t = T0; t < DUR - 1; t += BEAT, k++) { var pos = k % 4; if (pos === 0) { bump(low, t, 2.2, 12); bump(full, t, 2.0, 10); } else if (pos === 2) { bump(low, t, 1.8, 12); bump(full, t, 1.9, 10); } else { bump(full, t, 2.5, 8); bump(low, t, 0.9, 6); } bump(full, t + BEAT / 2, 1.0, 4); }
var lrc = d.parseLrc(BLURRY_LRC), ons = [], offs = [], firstIdx = [], lineText = [];
lrc.forEach(function (l) { if (!l.text) return; var K = d.syllableTexts(l.text).length, q; firstIdx.push(ons.length); lineText.push(l.text); for (q = 0; q < K; q++) { var on = l.t + 0.2 + q * 0.25; ons.push(on); offs.push(on + 0.2); sing(voice, on, on + 0.2); } });
var s = d.S(); s.time = '4/4'; s.bpm = 100; s.audio = null; s.lines = []; s.lyrics = ''; s.title = ''; s.filled = null; s.spotify = null; d.cur().undo = []; d.cur().redo = [];
d.cur().audio = { el: { paused: true, currentTime: 0, duration: DUR, playbackRate: 1, pause: function () {}, play: function () { return Promise.resolve(); } }, url: '', name: 'Puddle of Mudd - Blurry.wav', peaks: null, duration: DUR, onset: d.risesOf(full), voice: voice, low: low, blob: false };
var realFetch = window.fetch;
window.fetch = function (url, opts) { if (String(url).indexOf('/lyrics') === 0) return Promise.resolve({ ok: true, status: 200, headers: new Headers({ 'content-type': 'application/json' }), json: function () { return Promise.resolve({ ok: true, synced: BLURRY_LRC, plain: '', duration: DUR, track: 'Blurry', artist: 'Puddle of Mudd' }); } }); return realFetch(url, opts); };
d.autoPlaceWords().then(function () {
  var s1 = d.S(), sa = d.sheetAudio(), spb = d.slotsPerBar(s1.time), lines = [], all = [];
  s1.lines.forEach(function (l, li) { if (l.kind !== 'line') return; lines.push(l); var base = d.barOrdinal(s1, li, 0) * spb; d.sortedSyls(l).forEach(function (y) { if (!y.rest) all.push({ y: y, g: base + y.pos, li: li, bars: l.bars, base: base }); }); });
  say('LOG page ' + location.pathname.split('/').pop() + ': bpm ' + s1.bpm + ' time ' + s1.time + ' offsetSec ' + sa.offsetSec + ' locked ' + sa.locked + ' fit ' + JSON.stringify(sa.lockFit) + '; sheet lines ' + lines.length + ' (timed lines with words 55), syllables ' + all.length + ' of ' + ons.length + ' sung, total bars ' + d.player.bars.length);
  check('all 480 syllables on the sheet, in order', all.length === ons.length);
  var errs = [], off1 = 0, offHalf = 0, maxE = 0, sum = 0, packed = 0;
  all.forEach(function (a, q) { if (q >= ons.length) return; var e = d.songOfSlot(a.g) - ons[q]; errs.push(e); sum += e; if (Math.abs(e) > maxE) maxE = Math.abs(e); if (Math.abs(e) > SIXTEENTH) off1++; if (Math.abs(e) > SIXTEENTH / 2) offHalf++; if (q > 0 && a.g === all[q - 1].g + 1 && d.lenSlots(all[q - 1].y) === 1 && ons[q] - ons[q - 1] > 1.5 * SIXTEENTH) packed++; });
  check('every syllable within one sixteenth (' + r3(SIXTEENTH) + ' s) of where it was sung', off1 === 0, off1 + ' of ' + errs.length + ' off by more than a sixteenth, ' + offHalf + ' by more than half; max |err| ' + r3(maxE) + ' s, mean ' + r3(sum / errs.length) + ' s, packed-as-sixteenths pairs ' + packed);
  say('LOG first-syllable error per timed line (s): ' + firstIdx.map(function (q) { return r2(errs[q]); }).join(' '));
  var chorus = firstIdx.slice(8, 15).map(function (q) { return r2(errs[q]); }), bridge = firstIdx.slice(32, 47).map(function (q) { return r2(errs[q]); });
  say('LOG chorus 1 (lines 9-15) first-syllable errors: ' + chorus.join(' ') + '; bridge (lines 33-47): ' + bridge.join(' '));
  var last = toasts[toasts.length - 1] || '', sq = /(\d+) lines? starts?/.exec(last);
  say('LOG toast: ' + last);
  say('LOG lines with bars: ' + lines.map(function (l) { return l.bars; }).join(' '));
  // the chorus on the sheet: which sheet line holds "Can you take it all away?" lines 9-15 and where they sit
  var l9 = all[firstIdx[8]], l10 = all[firstIdx[9]]; say('LOG line 9 "Can you take it all away?" at slot ' + l9.g + ' (bar ' + (Math.floor(l9.g / spb) + 1) + ', sheet line starting bar ' + (l9.base / spb + 1) + ') placed ' + r2(d.songOfSlot(l9.g)) + ' s, sung ' + r2(ons[firstIdx[8]]) + '; line 10 at slot ' + l10.g + ' placed ' + r2(d.songOfSlot(l10.g)) + ' s, sung ' + r2(ons[firstIdx[9]]));
  check('no NaN styles', document.querySelectorAll('[style*="NaN"]').length === 0);
  check('player.bars relaid', d.player.bars.length === lines.reduce(function (a, l) { return a + d.lineBars(l, spb); }, 0), d.player.bars.length);
  window.fetch = realFetch;
}, function (e) { say('FAIL rejected: ' + (e && e.stack || e)); window.fetch = realFetch; });
